### ISSUE TITLE
Symfony 2.8.18 breaks '@hook option'

### ISSUE THREAD

**Issue by bwood** [consolidation/annotated-command#101]
This arguably is not a bug with annotated-command.  I'm just reporting and linking to https://github.com/symfony/console/pull/30 in case this info is useful to others.

### Steps to reproduce

1. Create an application with an annotated command which gets 1 option from the normal `@option` annotation and another option from a [`@hook option implementation`](https://github.com/consolidation/annotated-command#option-event-hook).
2. Pin symfony/console to 2.8.17 in your composer.json and run `composer update`.
3. Observe that both options work in with your command.
4.  Pin symfony/console to 2.8.18 in your composer.json and run `composer update`.
5. Observe that the option implemented with the hook stops working. If you set a break point in your command you can see that the value of the "hooked in" option is not updated when the option is passed.

This problem is also present when I test with symfony/console 3.2.

### Notes

Here's the [PR for symfony/console 2.8.18](https://github.com/symfony/console/commit/81508e6fac4476771275a3f4f53c3fee9b956bfa).

dsnopek writes:
> In the Symfony Console PR it appears the inputBound property is used to prevent $input->bind() from getting called multiple times.
However... this actually seems a little off. I don't know the Symfony Console code very well, but it seems to me that this would fail to bind and probably hide validation errors if the arguments/options failed to validate for some reason. This is because the first time $input->bind() is called, it just swallows any exceptions, but sets the inputBound property regardless. The 2nd time $input->bind() is called it does show validation errors, but it won't actually try to bind a 2nd time because inputBound is set. At least that's my interpretation just from looking at the code.

> I'm guessing that 'annotated-command' is updating the commands definition in the event, and was expecting Symfony Console to do the 2nd $input->bind() with the new definition. But since the inputBound property is set, it won't run it the 2nd time.

> Firstly, I think this is a bug in Symfony Console. If $input->setInputBound(true) only happens if the first bind is successful, then things work as expected. See this PR:
https://github.com/symfony/console/pull/30

> Or, possibly, I think the 'annotated-command' project could bind the $input to the new definition itself rather than depending on Symfony Console to do it later? I'm not sure which project will be easier to convince that there is something to fix.

### System Configuration
* php 5.6
* symfony/console 2.8.18

**Comment by greg-1-anderson** [comment]
Looks like 2.8.19 / 3.2.7 should clear up this problem.

For a while, I added a constraint to the annotated-command composer.json to restrict the version of Symfony that could be used  with the latest version of this project. Unfortunately, this caused Composer to give indeterminate results -- it would sometimes decide to choose the newest Symfony and an older annotated-command. Fortunately, this workaround is no longer needed.

**Comment by bwood** [comment]
Confirmed fixed!
