### ISSUE TITLE
createFinder() should set followSymlinks() on the symfony finder

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#107]
### Steps to reproduce

I created a symlink to a command folder into my drush command location folder.

### Expected behavior

The command should be picked up.

### Actual behavior

It's not, because Symfony finder doens't follow symlinks by default.

### System Configuration

OS X 10.11.6.

**Comment by greg-1-anderson** [comment]
#108

**Comment by greg-1-anderson** [comment]
Did not call followSymlinks() by default; client must explicitly ask for this behavior.

**Comment by greg-1-anderson** [comment]
Tagged 2.4.13

**Comment by joachim-n** [comment]
This is still an issue.

In particular, it prevents local development of command packages, since I can't install the command from a git clone. I'm trying to debug https://github.com/drupal-code-builder/drupal-code-builder-drush/issues/13#issuecomment-1956039585 and I can't.
