### ISSUE TITLE
what order are hooks of the same type called in?

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#113]
Is there a defined order for hooks of the same type, eg interact?

In particular, within a single commands class, is it:

- the order they are defined in the code
- alphabetical by method name
- arbitrary?

**Comment by greg-1-anderson** [comment]
Arbitrary / undefined. Note that `pre-interact` and `post-interact` are available to give some level of ordering. Beyond that, there is no priority level setting for precisely  adjusting hook order.

**Comment by claudiu-cristea** [comment]
@greg-1-anderson @joachim-n as hooks rely on Symfony event dispatcher, I think it would be a nice new feature to allow passing a priority along with the hook annotation. Maybe `@hook post-command cache:rebuild 300`?
