### ISSUE TITLE
shorter names for options

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#116]
Is there a way to specify a shorter version of an option?

For example, the way that 'git clean' has both --dry-run and -n.

**Comment by greg-1-anderson** [comment]
See the [options section of the Robo getting started guide](http://robo.li/getting-started/#options).

**Comment by joachim-n** [comment]
It would be really handy if the AC docs pointed to the Robo docs, as I had no idea that site existed -- nor had I really much of a clue that any command-related stuff would be in that component, since its description is that it's a task runner. So far I've been looking in Drush, AC, and Symfony Console for documentation and example code.

**Comment by greg-1-anderson** [comment]
The annotated commands library was factored out of Robo. The problem with pointing to the Robo site is that not everything documented in Robo is supported in Annotated Commands. There should be better documentation on everything in this repository, ideally.

**Comment by greg-1-anderson** [comment]
Note that we *do* have this note at the top of the README:
```
Note If you are looking for a very fast way to write a Symfony Console-base command-line tool, you should consider using Robo, which is built on top of this library, and adds additional conveniences to get you going quickly. See Using Robo as a Framework. It is possible to use this project without Robo if desired, of course.
```
