### ISSUE TITLE
Actual required PHP version is ^7.0.22 now

### ISSUE THREAD

**Issue by TeslaDethray** [consolidation/annotated-command#129]
### Steps to reproduce
1. Use Composer to install a version of Annotated Command ≤2.4.11 using 5.4.0 ≤ PHP < 7.0.22
2. Attempt to update to the newest version

### Expected behavior
The update should work without trouble on any PHP version ^5.4.0

### Actual behavior
The requirement for the dependency `phpdocumentor/reflection-docblock` ^4.0 is PHP ^7.0; Composer complains and fails accordingly

### System Configuration
Mac OS 10.12.6, PHP 5.5.38

**Comment by TeslaDethray** [comment]
This change was released in Annotated Command version 2.4.12. (I'll pin Terminus to 2.4.11 for now.)

It looks like it needs to have ^4.0 removed if you want to continue supporting PHP >7.0.

**Comment by greg-1-anderson** [comment]
The behavior of this will vary depending on what version of PHP you are running. For example, if you run `composer update` with php 7.1, you will get reflection-docblock ^4, but if you run with php 5.6, you will get an earlier version of reflection-docblock. 

To avoid this sort of problem in applications, you can set the platform php version in your composer.json. For an example of this, see the [Robo composer.json config section](https://github.com/consolidation/Robo/blob/1.1.3/composer.json#L61:L63).

Overall, though, `phpdocumentor/reflection-docblock` has caused a lot of problems. I think I am going to remove it, and use a bespoke docblock parser instead. That's what older versions of Robo did in the past, at some point before this library was factored out of it.

**Comment by greg-1-anderson** [comment]
Fixed in #130 -- phpdocumentor/reflection-docblock has been removed, so it should be easier to resolve Composer dependencies now.
