### ISSUE TITLE
allow init hooks to have an $output parameter

### ISSUE THREAD

**Issue by joachim-n** [consolidation/annotated-command#132]
As in the example in the docs, I am using the init hook to set a some option values to defaults if they were not given on the command line.

What I'd like to do when this happens is notify the user, .e.g:

> Foo option has been set to 'bar'.

However, the hook doesn't appear to allow an $output parameter.

**Comment by greg-1-anderson** [comment]
Inject a logger via LoggerAwareInterface, and use that.

**Comment by greg-1-anderson** [comment]
If you are setting defaults to command options, then you should use consolidation/config, which will do this for you.

Drush and Robo are both already using this project.

Also, if the option is coming from $input, then of course it should already have a place to put a default value.

**Comment by joachim-n** [comment]
The default value is dynamic: if the parameter is '.', it should be changed to the current working directory. Is that doable in config?

And yes, I have $Input to put default value, but I want to announce to the user that this has happened, with $output.

Could you reopen please? I think you've missed the point of what I was asking.

Is this ->io() available during an init hook?

**Comment by greg-1-anderson** [comment]
`io()` and `$output` were deliberately excluded from the hook init parameters to discourage commands doing user interaction at this stage. If you want to notify the user of something in an init hook, then you should instead use a logger. You can do this via `LoggerAwareInterface` / `LoggerAwareTrait`.

**Comment by joachim-n** [comment]
>  If you want to notify the user of something in an init hook, then you should instead use a logger.

Sending if to the log doesn't really do what I'm after. I'd like to inform the user that a default value is being used for an option.

**Comment by greg-1-anderson** [comment]
The logger outputs to the console.

**Comment by joachim-n** [comment]
This works in my init hook:

```
$this->io()->text()
```

**Comment by greg-1-anderson** [comment]
`$this->logger` is preferred.

**Comment by joachim-n** [comment]
That seems a bit weird from a semantic POV. The logger feels like something that *might* get output to console, but isn't necessarily, depending on what the app feels like doing / what the user has configured.
