### ISSUE TITLE
Single-command app

### ISSUE THREAD

**Issue by mikeshiyan-lc** [consolidation/annotated-command#139]
### Steps to reproduce
There's a way to create a single-command tool in the Symfony Console with such line:
```
$app->setDefaultCommand('my-command', TRUE);
```
to use the tool like this:
```
./my-command arguments
```
Unfortunately, this case is skipped in the Annotated Command.

### Expected behavior
The command should be executed normally.

### Actual behavior
The first argument, inputted in the command line, is skipped when my-command method is called.

### System Configuration
Linux Mint 18.3 64-bit, PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 ( NTS )

**Comment by greg-1-anderson** [comment]
Did you call `$app->setDefaultCommand()` in your application?

**Comment by mikeshiyan** [comment]
Yes, between calls `$app->add` and `$app->run`.

**Comment by greg-1-anderson** [comment]
I haven't tried to reproduce, but this situation is a bit confusing. `$app->run()` is entirely responsible for command dispatching, as controlled by your `ArgvInput` object. The annotated command library plays no part. Or so I would expect, anyway. If you discover anything here causing problems with this functionality, I would certainly be amendable to a fix.

**Comment by mikeshiyan** [comment]
Seems like it happens here - https://github.com/consolidation/annotated-command/blob/master/src/CommandData.php#L173

**Comment by greg-1-anderson** [comment]
Ugh, that is terrible. Try #139 -- it is marginally better.

**Comment by mikeshiyan-lc** [comment]
Perfect! I tested both single- and multi-command with your change, both works. Thanks, Greg!

**Comment by greg-1-anderson** [comment]
I'll tag a new stable version shortly.

**Comment by greg-1-anderson** [comment]
Tagged 8.2.3
