### ISSUE TITLE
Cancel a command via hook.

### ISSUE THREAD

**Issue by dpagini** [consolidation/annotated-command#145]
Forgive me for not using the issue template, but I think this is more a question/idea than a specific bug.

I am wondering if there is some ability to cancel a command via a hook? I am using a library that is using robo, and I am able to hook into a command, and I thought I could use something like the validate hook to check for some condition, and ultimately see if I want to allow my command to run based on certain criteria. If the criteria is met, I would love to be able to cancel the command execution, print a helpful message, but still return a successful exit code.

This does not seem possible with validation, as you can only return a CommandError or throw an exception, both which end up in the whole process being killed.

Thoughts? Thanks in advance for any help or ideas....

**Comment by greg-1-anderson** [comment]
This can be accomplished with a Symfony [ConsoleEvents::COMMAND event]( https://symfony.com/doc/current/components/console/events.html). In general, the Symfony native hooks can be added via annotation hooks, but I can't remember off the top of my head if/how to do that with `ConsoleEvents::COMMAND`. I can look into it later if it's not clear; ping me again if I forget.

(Use of the issue template is not required.)

**Comment by greg-1-anderson** [comment]
The documentation is pretty light, but the command event hook is just `@hook command`:

https://github.com/consolidation/annotated-command#command-event-hook

I expect the parameters to this hook should be the same as in the Symfony documentation. If you get this working, a documentation PR would be most appreciated.
