### ISSUE TITLE
How to set options programmatically in command so they are available to post-command hook?

### ISSUE THREAD

**Issue by pyrello** [consolidation/annotated-command#189]
This is technically a support request, so maybe this is not the right place to file this. I didn't see in the contributing guidelines anything about support requests, or I missed it.

I am using the `replace-command` hook to override the `recipes:multisite:init` command provided as part of BLT. I'm also using the `post-command` hook to run some additional operations. Within the `replace-command` method, how do I set option values so that they will be available in the `post-command` hook? In the `post-command` hook, there is a CommandData object that I can lookup options in, but there doesn't seem to be a corresponding way inside the command itself to set options in a way that they later show up in the CommandData object.

I'm probably missing something obvious. Any help is appreciated.

Thanks,

Sean

**Comment by greg-1-anderson** [comment]
If you were defining the command in your application, you could make the first parameter an InputInterface; then, you could just set options on the $input option, and they should be available through the CommandData once you get to the `post-command` hook. This will be the recommended way to write commands in Robo 2.0.

Since BLT did not give you a reference to the $input object, the best you can do is recover it via the static accessor. Robo provides a static `Robo` class that contains methods to access config, input, etc; this is not the recommended way to write your command handlers, but if you have no other option, it should work.

**Comment by pyrello** [comment]
@greg-1-anderson Thanks for the prompt reply!

If I wanted to re-factor my code to create a custom command rather than using the `replace-command` hook and do it the recommended way, I see an example I can follow here: https://github.com/consolidation/annotated-command/blob/master/tests/src/ExampleAnnotatedCommand.php#L47

Here is what I came up as a replacement for the existing method definition:
```php
  /**
   * Generates a new multisite.
   *
   * @command uiowa:multisite
   * @option string $site-dir
   * @option string $site-uri
   * @option string $remote-alias
   *
   * @aliases um uimultisite
   */
  public function generate(InputInterface $input, OutputInterface $output) {
    $site_dir = $input->getOption('site-dir');
    // ...
  }
```

Does that look right? Thanks for your assistance.

**Comment by greg-1-anderson** [comment]
Making your own command is definitely cleaner.

I don't remember if Robo provides a SymfonyStyle or if SymfonyStyle gives you a reference to $input, but that might be another way to go rather than using both InputInterface and OutputInterface, if it works.

**Comment by pyrello** [comment]
I'm not sure I understand your last comment. For my command, I'm not sure I actually need the OutputInterface argument, so maybe I could just leave it out?

As in:
```php
  /**
   * Generates a new multisite.
   *
   * @command uiowa:multisite
   * @option string $site-dir
   * @option string $site-uri
   * @option string $remote-alias
   *
   * @aliases um uimultisite
   */
  public function generate(InputInterface $input) {
    $options = $input->getOptions();
    // ...
  }
```
