### ISSUE TITLE
Support PHP8 attributes in addition to annotations

### ISSUE THREAD

**Issue by weitzman** [consolidation/annotated-command#215]
PHP8 is released! Ideally PHP8-only sites can author using [attributes](https://www.php.net/releases/8.0/en.php#attributes) and these commands are recognized in addition to commands that use annotations. We're going to be in this dual world for a long time.

**Comment by weitzman** [comment]
I looked into this a bit. 

Attributes Classes
--------
[PHP docs are laughably sparse](https://www.php.net/manual/en/language.attributes.php). We'll need to create small classes for each "annotation" we support. 

Parsing
----------
`\Consolidation\AnnotatedCommand\Parser\Internal\CommandDocBlockParserFactory::parse` currently always creates a `BespokeDocBlockParser`. I think we could make a new `AttributesDocBlockParser` for the Attributes case. Use Reflection to determine if we have an Attributes class and again use it to get data from each "docblock". Are they still called docblocks? 

Open issues
-------------
- Do we still use `@param` and method arguments as we do today? Seems like we need method arguments to make the values available to the method body.
- Do we still use a final argument for $options? Do we still declare default values there or move that to an Attribute?

**Comment by beejeebus** [comment]
I'll take a stab at this. I have some WIP code, will post soon.

**Comment by beejeebus** [comment]
put up a draft PR. definitely lots of cut and paste, probably requires some refactoring, but seems to work for the basic tests.

feedback please!

**Comment by weitzman** [comment]
Done in #221. Thanks!
