### ISSUE TITLE
Symfony 5.2

### ISSUE THREAD

**Issue by alsar** [consolidation/annotated-command#217]
Is there a reason that it's not allowed to use this with symfony/console v 5.2? 
`"symfony/console": "^4.4.8|~5.1.0",`

**Comment by greg-1-anderson** [comment]
Hm, looks like I did that recently, here: https://github.com/consolidation/annotated-command/pull/216

I don't remember why now. Relax the constraint and see what happens? PRs welcome.

**Comment by spipu** [comment]
Hi !
we have the same pb with symfony 5.3

**Comment by spipu** [comment]
Hi, 
any news about compatibility with symfony 5.2 and 5.3 ? because actually it locks the update of some others packages.

FYI, it was working in the v4.2.1 https://github.com/consolidation/annotated-command/blob/4.2.1/composer.json

**Comment by greg-1-anderson** [comment]
Discussion in https://github.com/consolidation/annotated-command/pull/220

**Comment by spipu** [comment]
ok you can clause this one
