### ISSUE TITLE
Avoid parsing methods from Traits

### ISSUE THREAD

**Issue by weitzman** [consolidation/annotated-command#234]
For our use case, we could use reflection to find the name of the file that the method is in, and skip it if it contains "Trait".
https://stackoverflow.com/questions/30661997/php-reflection-how-to-know-if-a-method-property-constant-is-inherited-from-trai/45912866 h/t @greg-1-anderson 

This will save parse time in Drush at least as every commandfile inherits traits from DrushCommands base class.

**Comment by weitzman** [comment]
I implemented this locally and it does help (see holes in the first array below). We could do more:

1. Here are methods to parse for Drush's SQLCommands. The last 4 methods are re-parsed for every command because [Robo\Common\IO.php](https://github.com/consolidation/Robo/blob/3.x/src/Common/IO.php) is a trait included by [DrushCommands](https://github.com/drush-ops/drush/blob/10.x/src/Commands/DrushCommands.php). Could IO.php be renamed to IOTrait or change these methods to protected?
```
Array
(
    [0] => conf
    [1] => connect
    [2] => create
    [3] => drop
    [4] => cli
    [5] => query
    [6] => dump
    [7] => validate
    [9] => preHook
    [21] => currentState
    [22] => restoreState
    [23] => setInput
    [24] => setOutput
)
```
2. Drush discovers Generators which are Symfony Console commands. The methods below are every Console command AFAICT. Here are the methods for [MigrateGenerator](https://github.com/drush-ops/drush/blob/10.x/src/Commands/generate/Generators/Migrate/MigrationGenerator.php). We dont actually need parsing for Console commands. Drush is just using the Drupal Service Container to store the [list of Generators that come from modules](https://github.com/drush-ops/drush/blob/641298c5988301e5fe12acac4ec3220d19411889/src/Commands/generate/GenerateCommands.php#L142-L142). 
```
Array
(
    [0] => getLabel
    [1] => getFiles
    [2] => getAssets
    [3] => setDirectory
    [4] => getDirectory
    [5] => setDestination
    [6] => getDestination
    [9] => ignoreValidationErrors
    [10] => setApplication
    [11] => setHelperSet
    [12] => getHelperSet
    [13] => getApplication
    [14] => isEnabled
    [15] => run
    [16] => setCode
    [17] => mergeApplicationDefinition
    [18] => setDefinition
    [19] => getDefinition
    [20] => getNativeDefinition
    [21] => addArgument
    [22] => addOption
    [23] => setName
    [24] => setProcessTitle
    [25] => getName
    [26] => setHidden
    [27] => isHidden
    [28] => setDescription
    [29] => getDescription
    [30] => setHelp
    [31] => getHelp
    [32] => getProcessedHelp
    [33] => setAliases
    [34] => getAliases
    [35] => getSynopsis
    [36] => addUsage
    [37] => getUsages
    [38] => getHelper
)

```

**Comment by greg-1-anderson** [comment]
1. My preference would be to make the methods protected. Would require a new major version of Robo. We could also just special-case IO.php in addition to files that end in "Trait".

2. Didn't look at the code for the generators, but is there any reason these have to be command files at all? i.e. do they use hooks?

**Comment by weitzman** [comment]
1. Special case sounds easier than involving Robo. Will do that.
1. They dont have to be commandfiles but [they expect Drupal services to be injected.](https://github.com/sananeyazi1/new_aug/blob/cbfa2f751834dec7594f01875eb70dd26319da17/docroot/modules/contrib/migrate_file_to_media/drush.services.yml#L10) The goal is for modules to ship with Generators. For consistency, we told people to [declare them in drush.services.yml with a `drush.generator` tag](https://www.drush.org/latest/generators/). Happy to do something else.

**Comment by Jelle-S** [comment]
@greg-1-anderson The fix for this introduced a BC break, where our Robo file uses traits we've written ourselves, where the filenames end in Trait, that contain commands that are now no longer detected. This is a BC break and should therefore have been a major version I think? This bug was introduced when upgrading from 4.3.1 to 4.3.2

**Comment by greg-1-anderson** [comment]
OK, maybe we need to add a flag to enable trait-parse skipping, and default it to false.

@Jelle-S Defining commands in a trait sounds unusual. Why do you do this? Do you instantiate the same command in multiple classes in the same program, or is this how you distribute commands from a library?

**Comment by Jelle-S** [comment]
Yes, it's basically how you distribute commands from a library. I do admit that it was written in a bit of a hurry in the earlier days of Robo, and could probably do with a rewrite/refactor, but we haven't got the time/budget for it atm. A flag would be nice at least, or a major version would be fine too. It's just that right now we had a bit of a scare when our deploy failed after doing a `composer update`, when none of the commands on our end had any changes at all.

**Comment by greg-1-anderson** [comment]
Sorry about the scare. We'll definitely fix the BC break. I'm undecided about whether we turn the feature on by default in AC 5.x. Could you take a look at Robo plugins, and see if that is a workable way for you to distribute commands from a library? If you can add traits, then I imagine you have your own executable and can add plugins as well, but lmk if you are using the distributed robo.phar and just `include`-ing some traits.

**Comment by weitzman** [comment]
See #241 for follow-up
