### ISSUE TITLE
Support autocomplete with Symfony Console 5.4+

### ISSUE THREAD

**Issue by weitzman** [consolidation/annotated-command#243]
See https://symfony.com/blog/new-in-symfony-5-4-console-autocompletion. ZSH completion in progress at https://github.com/symfony/symfony/issues/43592

**Comment by Sweetchuck** [comment]
`$ composer why-not 'symfony/console' '5.4'`
> consolidation/annotated-command  4.4.0  requires  symfony/console (^4.4.8|~5.1.0)

Is there any reason to use `~5.1` version constraint?

**Comment by weitzman** [comment]
Discuss at https://github.com/consolidation/annotated-command/pull/220

**Comment by weitzman** [comment]
See #264
