### ISSUE TITLE
Options provided by 'options' hook don't appear in command help

### ISSUE THREAD

**Issue by bwood** [consolidation/annotated-command#73]
### Steps to reproduce
Implement an options hook:

```php
class StepCommandOptions {

  /**
   * @hook option @stepoption
   * @option global-list Global list blah.
   */
  public function stepOptions();
```

In the command desiring the options from the hook add this annotation:
```php
  /**
   * @stepoption
   *
   * @command test:step-command
   *
   * @option bool $list List the steps for this command.
   */
  public function stepCommand($options = [
    'list' => FALSE,
  ]) {

```
In the application file use code like that in [Terminus.php](https://github.com/pantheon-systems/terminus/blob/master/src/Terminus.php#L161) to make the hook code available to the application:

```php
/**
   * Add the commands and hooks which are shipped with core Wps
   *
   * @param $container
   */
  private function addBuiltInCommandsAndHooks($container) {

    // Add the built in commands.
    $commands = $this->getCommands([
      'path' => __DIR__ . '/Commands',
      'namespace' => 'Wps\Console\Commands',
    ]);

    // Add the built in hooks
    $hooks = [
      'Wps\Console\Hooks\StepCommandOptions',
    ];
    $this->commands = array_merge($commands, $hooks);
  }

```

### Expected behavior
I should see 'global-list' in the output of `wps test:step-command -h`

### Actual behavior
```
$ php bin/wps.php test:step-command -h
Usage:
  test:step-command [options]

Options:
      --list            List the steps for this command.
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

### System Configuration
Darwin Kernel Version 15.6.0

**Comment by greg-1-anderson** [comment]
In your description, `In the command desiring the options from the hook:` appears to be accidentally duplicated from the previous section.

**Comment by bwood** [comment]
Oops. I just fixed the unintentionally duplicated code.  And I updated the other snippets to reflect the exact code I'm using. 

When I run the command without `-h` I get the 'global-list' option. When I run it with `-h` I don't see 'global-list' in the command help.  If I make the change in the PR, everything works as expected, but I acknowledge that the PR is probably not the correct fix since it fails that test. 

> Maybe you should try duplicating what the test is doing in your application, and see if it works.

My application uses Robo as a framework.  I'm doing exactly what terminus 1.0.0 is doing. But Terminus doesn't use the options hook anywhere. (Maybe terminus would have the same problem I have...?)  Suggestions welcome.  I'll study the test more and also the option hook examples in Drush...

**Comment by bwood** [comment]
[Attached is 0001-test-implementation-of-ann-cmd-option-hook.patch.txt](https://github.com/consolidation/annotated-command/files/749357/0001-test-implementation-of-ann-cmd-option-hook.patch.txt) demonstrating my attempt to implement the options hook on the HEAD of terminus.  It behaves exactly like my application (without -h I get the 'global-list' option. When I run it with -h I don't see 'global-list' in the command help.)  If you can see where I've gone wrong, I'll happily make a PR to the annotated-command docs to clarify how to use the options hook.

I added this to site:info:
```
$ php bin/terminus site:info -h
Usage:
  site:info [options] [--] <site>
  site
  site:info <site> Displays <site>'s information.

Arguments:
  site                   The name or UUID of a site to retrieve information on

Options:
      --format[=FORMAT]  Format the result data. Available formats: csv,json,list,php,print-r,string,table,tsv,var_export,xml,yaml [default: "table"]
      --fields[=FIELDS]  Available fields: ID (id), Name (name), Label (label), Created (created), Framework (framework), Organization (organization), Service Level (service_level), Upstream (upstream), PHP Version (php_version), Holder Type (holder_type), Holder ID (holder_id), Owner (owner), Is Frozen? (frozen) [default: ""]
      --field[=FIELD]    Select just one field, and force format to 'string'. [default: ""]
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
  -y, --yes              Answer all confirmations with "yes"
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by greg-1-anderson** [comment]
Fixed in HEAD of master. Thanks for reporting this.
