### ISSUE TITLE
Support for an array option

### ISSUE THREAD

**Issue by frol-kr** [consolidation/annotated-command#77]
I think that it would be nice if there were a possibility to have an array type.

**Comment by greg-1-anderson** [comment]
Could you please give an example of 

1. What you would like to enter on the commandline
2. What format you would like to see that data passed to your command function

**Comment by greg-1-anderson** [comment]
Explained in #78

**Comment by frol-kr** [comment]
Provided a [draft pr](https://github.com/consolidation/annotated-command/pull/78) there are a few examples.
