### ISSUE TITLE
Confusion of setting up a mode and default values

### ISSUE THREAD

**Issue by frol-kr** [consolidation/annotated-command#79]
Probably, it could be easily argued that it's confusing because I am new to this library and at the first place didn't know what i was doing back then. However I think that this thing is worth to mention that the way you define the mode and default values of options for the command is a bit confusing.

As an example, if you want to have a default value to be equal 2, there are two ways (as far as I know) of doing so. The first is through the annotation which works fine and the second one is through the default values of arguments of a function which could behave as you may not expect.

Ex.
I started to use this lib with robo framework, where I wanted to run my tests in two threads as a default arg.
```php
public function parallelRunTest(array $opts = ['threads|t' => 2, 'suite|s' => 'api'])
```
Here I wanted the `threads` to be equal 2 as default value but it turns out that 2 (```phpInputOption::VALUE_REQUIRED```) is equal a constant that specifies that this field is required, the other option will work though. So the only way is to do it though the annotation like this:
```php
/**
* @option int $threads Number of threads to use for running the tests
* @default int $threads 2
*/
public function parallelRunTest(array $opts = ['threads|t' => null, 'suite|s' => 'api'])
```

**Comment by greg-1-anderson** [comment]
The default value for options should always be **strings**, not integers. So, to fix your default value (without using @default, which is also okay), use `$opts = ['threads|t' => '2']`.

I pushed some more tests and updated the README on `master` to clarify this point.
