### ISSUE TITLE
Document variable amount of arguments

### ISSUE THREAD

**Issue by Jelle-S** [consolidation/annotated-command#87]
This was briefly discussed on Twitter:
https://twitter.com/sebreghtsjelle/status/835124401616076801

```php
/**
 * Documentation for mynamespace:my-command
 * 
 * @param array $arguments
 *   Variable amount of arguments. Last 2 arguments are SSH username and password.
 *   All remaining (first x) arguments are servers to execute a command on.
 */
public function mynamespaceMyCommand(array $arguments) {
}
```

How would we document individual arguments for this command?
Might be related to #69.

**Comment by greg-1-anderson** [comment]
This specific command would be easier to document if the ssh username and password were the first arguments rather than the last.

**Comment by greg-1-anderson** [comment]
Nothing to do here, as far as I can tell.
