### ISSUE TITLE
Support @inheritdoc

### ISSUE THREAD

**Issue by Jelle-S** [consolidation/annotated-command#88]
Is there a way we can support phpdoc inheritance: https://www.phpdoc.org/docs/latest/guides/inheritance.html

All of `@inheritdoc`, `@inheritDoc`, `{@inheritdoc}` and `{@inheritDoc}` would need to be supported.
The variants with the `{}` are used to import the docblock of the parent in the current docblock.

We're looking to create a package with a RoboFileBase for our CI tool. Each project can have a RoboFile that extends that class and can overwrite the commands. It would be nice if we could use the docblock inheritance to provide the documentation on the command line.

**Comment by greg-1-anderson** [comment]
Have you considered extending the commands with the `@hook` mechanism?

Implementing @inheritdoc is a possibility; it could cause problems, though, in environments where both the base class and the derived class cause the same command to be created. I don't know that there's a good way, at the time the commands are added to the Application, to distinguish between them.

I'm not likely to implement this myself in the near future, but would be open to a PR if the edge cases are adequately addressed.

**Comment by greg-1-anderson** [comment]
Closed for lack of activity.
