### ISSUE TITLE
init hook and command-event

### ISSUE THREAD

**Issue by weitzman** [consolidation/annotated-command#89]
### Steps to reproduce
1. I tried to use the initialize hook per README.md
2. I tried to use command-event hook

### Expected behavior
Both should work

### Actual behavior
1. Initialize hook is actually called init. Lets fix docs.
1. I was not able to get command-event to fire for a Drush command in quick testing.

### System Configuration
OSX 10.11

**Comment by greg-1-anderson** [comment]
The big question here is, are we going to dump the Drush command event processor, and use Symfony console?  The command-event hook is fired by Symfony Console. It is not supported by the command adapter. I'm not sure which other hooks are unimplemented; I only did a few of the key ones.

The easiest way to satisfy this requirement would be to just use Symfony Console. I suspect it would still be a lot of work to make the adapter match the behavior exaclty.

**Comment by weitzman** [comment]
Console dispatch is in our future. Could be Drush 9 or Drush 10. Lets just wait.
