### ISSUE TITLE
@return on plugin command methods is unforgiving

### ISSUE THREAD

**Issue by TeslaDethray** [consolidation/annotated-command#91]
From https://github.com/pantheon-systems/terminus/issues/1503
Added to Jira in BUGS-1138

### Expected behavior
The following two command declarations should behave identically:

```php
/**
 * @command foo:bar
 * @field-labels
 *   foo: Foo Label
 *   bar: Bar Label
 * @return PropertyList
 */
public function fooBar() {
  // Returns the following property list in a formatted table.
  return new PropertyList(['foo' => 'foo val', 'bar' => 'bar val']);
}
```

```php
/**
 * @command foo:bar
 * @field-labels
 *   foo: Foo Label
 *   bar: Bar Label
 * @return PropertyList Comment for myself in code.
 */
public function fooBar() {
  // Returns an unformatted list of the values below.
  return new PropertyList(['foo' => 'foo val', 'bar' => 'bar val']);
}
```

### Actual behavior
When authoring a plugin for terminus 1.x, if my `@return` declaration in my docblock includes comments after the return type of `RowsOfFields` or `PropertyList`, the returned output is not formatted as expected.

### Steps to reproduce the behavior
See above.

**Comment by greg-1-anderson** [comment]
Fixed in #130
